<?php
	use PHPMailer\PHPMailer\PHPMailer;
	use PHPMailer\PHPMailer\SMTP;
	use PHPMailer\PHPMailer\Exception;

	require '../PHPMailer/DSNConfigurator.php';
	require '../PHPMailer/Exception.php';
	//require '../PHPMailer/OAuth.php';
	require '../PHPMailer/PHPMailer.php';
	require '../PHPMailer/POP3.php';
	require '../PHPMailer/SMTP.php';

	require '../vendor/autoload.php';

	$emailRemetente = $_POST['email'];
	$nomeRemetente = $_POST['nome'];
	$mensagemRemetente = $_POST['mensagem'];
	$telefone = $_POST['tel'];

	header('Location: /');

	$mail = new PHPMailer(true);

try {
    //Server settings
    $mail->SMTPDebug = SMTP::DEBUG_SERVER;                      //Enable verbose debug output
    $mail->isSMTP();                                            //Send using SMTP
    $mail->Host       = 'smtp.gmail.com';                     //Set the SMTP server to send through
    $mail->SMTPAuth   = true;                                   //Enable SMTP authentication
    $mail->Username   = 'user@gmail.com';                     //SMTP username
    $mail->Password   = 'wjokypwsttwmnpvz';                               //SMTP password
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;            //Enable implicit TLS encryption
    $mail->Port       = 465;                                    //TCP port to connect to; use 587 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS`

    //Recipients
    $mail->setFrom($emailRemetente, 'Remetente');
    $mail->addAddress('user@gmail.com', 'Destinatário');     //Add a recipient
    //$mail->addAddress('ellen@example.com');               //Name is optional
    //$mail->addReplyTo('info@example.com', 'Information');
    //$mail->addCC('cc@example.com');
    //$mail->addBCC('bcc@example.com');

    //Attachments
    //$mail->addAttachment('/var/tmp/file.tar.gz');         //Add attachments
    //$mail->addAttachment('/tmp/image.jpg', 'new.jpg');    //Optional name

    //Content
    $mail->isHTML(true);                                  //Set email format to HTML
    $mail->Subject = 'Contato de: '.$nomeRemetente;
    $mail->Body    = $mensagemRemetente.'<br>'.'Segue o meu telefone para contato'.$telefone;
    $mail->AltBody = 'Necessário navegador menos merda';

    $mail->send();
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}
?>
