<!-- Cabeçalho padrão -->
<header class="bg-dark sticky-top">
	<div class="container-fluid">
		<div class="row">
			<div class="col">
				<nav class="navbar bg-dark">
					<div class="navbar-brand">
						<a href="/"> <img class="logos ms-4 p-2" src="/img/logo.png"></a>
					</div>
					<div class="d-flex">
						<h3><a class="preto ms-2" href="/sobre">Sobre</a></h3>
						<h3><a class="preto ms-2" href="/trabalhos">Trabalhos</a></h3>
						<h3><a class="preto ms-2 me-5" href="/contato">Contato</a></h3>
					</div>
				</nav>
			</div>
		</div>
	</div>
</header>
<!-- fim -->
<!-- Apresentação trabalhos -->
	<div class="container-fluid">
		<div class="row">
			<div class="col-12">
				<h1 class="text-center display-3">Fotos de Casamentos</h1>
				<img src="/img/casados.jpg" style="width: 350px; height: 350px; border-radius: 50px; margin-left: 8em;">
				<img src="/img/casados2.jpg" style="width: 350px; height: 350px; border-radius: 50px; margin-left: 5em;">
				<img src="/img/casados3.jpg" style="width: 350px; height: 350px; border-radius: 50px; margin-left: 5em;">
			</div>
			<div class="col-12 mb-5">
				<h1 class="text-center display-3">Fotos de Animais</h1>
				<img src="/img/gato1.jpg" style="width: 350px; height: 350px; border-radius: 50px; margin-left: 8em;">
				<img src="/img/gatos1.jpg" style="width: 350px; height: 350px; border-radius: 50px; margin-left: 5em;">
				<img src="/img/gatos2.jpg" style="width: 350px; height: 350px; border-radius: 50px; margin-left: 5em;">
			</div>
		</div>
		
	</div>
<!-- Rodapé padrão -->
<footer>
	<div class="container-fluid bg-dark">
		<div class="row p-3 mb-3">
			<div class="col-4">
				<h4 class="text-white">Redes Sociais</h4>
				<span class="text-white"><i class="fa-brands fa-twitter fa-2xl ms-2 mt-5"></i></span>
				<span class="text-white"><i class="fa-brands fa-facebook fa-2xl ms-2"></i></i></span>
				<span class="text-white"><i class="fa-brands fa-instagram fa-2xl ms-2"></i></i></span>
			</div>
			<div class="col-4">
				<h4 class="text-white">Informações</h4>
				<br>
				<a href="/sobre">Sobre</a><br>
				<a href="/trabalhos">Trabalhos</a>
			</div>
			<div class="col-4 ">
				<h4 class="text-white">Contato</h4>
				<br>
				<div class="d-flex">
					<i class="fa-solid fa-phone text-white"></i><h5 class="text-white ms-2" style="font-size: 0.9em;">(99) 99999-9999</h5>
				</div>
				<div class="d-flex">
					<i class="fa-solid fa-envelope text-white"></i><h5 class="text-white ms-2" style="font-size: 0.9em;">emailteste@teste.com</h5>
				</div>
				
				

			</div>
			
		</div>
		<div class="bg-dark p-3">
			<h2 class="text-white text-center">Created By @denilson</h2>
		</div>
	</div>
	
</footer>
<!-- fim -->